### ISSUE TITLE
Great work - 1 bug

### ISSUE THREAD

**Issue by viztastic** [tarlepp/angular-cli-frontend#1]
Just wanted to drop in a note and say this is really handy @tarlepp , thanks!

When I run `ng serve` I get this error in the console:

![image](https://cloud.githubusercontent.com/assets/8556736/25510487/c67c07c0-2c03-11e7-9194-767b05839738.png)

**Comment by tarlepp** [comment]
You haven't created required `env.js` file - there are instructions on [README](https://github.com/tarlepp/angular-cli-frontend/blob/master/README.md#configuration) about this
