### ISSUE TITLE
Both the frontend and the backend are working perfectly, thank you for sharing. How can I add the entities Author and Books into the frontend?

### ISSUE THREAD

**Issue by Kasu0708** [tarlepp/angular-cli-frontend#3]

**Comment by tarlepp** [comment]
Eg. by making simple HTTP request to backend side.

**Comment by Kasu0708** [comment]
yes, if I make a simple HTTP request with the uri (http://192.168.6.33:8000/author). I get the unauthorized error code 401.

**Comment by Kasu0708** [comment]
even thou I have already logged in with the admin.

**Comment by tarlepp** [comment]
And are you sure that you're sending Authorization header on those request within your login JWT? Also what do you mean with `even thou I have already logged in with the admin.`?

**Comment by tarlepp** [comment]
Also what are you using with your backend ?

**Comment by Kasu0708** [comment]
This is the post service`import { Injectable } from '@angular/core';
import {Http, Response, Headers } from '@angular/http';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/catch';
import 'rxjs/add/operator/map';
import 'rxjs/add/observable/throw';
import {Post} from './Post';
import {AuthService} from './auth.service';

@Injectable()
export class PostService {

  private uri= 'http://127.0.0.1:8000/api/posts';



  constructor(private http: Http, private authenticationService: AuthService  ) {}

  getPosts(): Observable<any[]> {
    const headers = new Headers({ 'Authorization': 'Bearer ' + this.authenticationService.token });
    return  this.http.get(this.uri , {headers : headers}).map(res => <Post[]> res.json() ).catch(this.handelError);

  }

  addPost(post: Post) {
    const  headers = new Headers();
    headers.append('content-type', 'application/json');
    headers.append('Authorization', 'Bearer ' + this.authenticationService.token);
    return this.http.post(this.uri, JSON.stringify(post), {headers : headers}).map(res => res.json()).catch(this.handelError);
  }



  updatePost(post: Post , id) {
    const  headers = new Headers();
    headers.append('content-type', 'application/json');
    headers.append('Authorization', 'Bearer ' + this.authenticationService.token);
    return this.http.put(this.uri + '/' + id, JSON.stringify(post), {headers : headers}).map(res => res.json()).catch(this.handelError);
  }


  deletePost(id: any) {
    const  headers = new Headers();
    headers.append('Authorization', 'Bearer ' + this.authenticationService.token);
    return this.http.delete(this.uri + '/' + id, {headers : headers}).map(res => res.json());
  }


  private handelError(error: Response) {

    return Observable.throw(error.json().errors || 'server error');

  }

}`

I am using the symfony-backend.

**Comment by tarlepp** [comment]
Hmm that doesn't contain anything about `How can I add the entities Author and Books into the frontend?`  - confused atm.

**Comment by tarlepp** [comment]
and really i recommend that you use https://github.com/auth0/angular2-jwt library to make those requests. And could you confirm that your requests use that header key + value?

**Comment by Kasu0708** [comment]
Thank you for the assistance. It is working now, the issue was with the service component.
